http:
  address: 0.0.0.0:80
users:
  - name: admin
    password: $2b$10$kzcifmKRUpCZOV2XoPzPLumTAn17rCt/Sen.FGO3idpuataWVw2Ue
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  upstream_dns:
    - 172.23.0.10
  bootstrap_dns:
    - 172.23.0.10
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
querylog:
  ignored:
    - healthcheck.local
statistics:
  ignored:
    - healthcheck.local
filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: false
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    name: AdAway Default Blocklist
    id: 2
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt
    name: Dan Pollock's List
    id: 1739486973
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt
    name: Peter Lowe's Blocklist
    id: 1739486974
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_62.txt
    name: Ukrainian Security Filter
    id: 1739486975
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt
    name: Steven Black's List
    id: 1739486976
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
    name: Phishing URL Blocklist (PhishTank and OpenPhish)
    id: 1739486977
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_18.txt
    name: Phishing Army
    id: 1739486978
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt
    name: uBlock₀ filters – Badware risks
    id: 1739486979
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
    name: Malicious URL Blocklist (URLHaus)
    id: 1739486980
